import { defineConfig } from 'vite-plus'

export default defineConfig({
  test: {
    include: ['test/**/*.test.mjs'],
    fileParallelism: false,
  },
  fmt: {
    semi: false,
    singleQuote: true,
    trailingComma: 'all',
    sortPackageJson: false,
    ignorePatterns: ['.agents/**', '.claude/**', 'pnpm-lock.yaml', 'skills-lock.json'],
  },
  lint: {
    env: {
      node: true,
    },
    // Example entry points import declarations generated by `swift-node build`.
    // Their platform-specific build-and-test CI jobs validate them after that output exists.
    ignorePatterns: [
      '.agents/**',
      '.claude/**',
      'examples/**',
      '**/dist/**',
      '**/dist_swift-node/**',
    ],
    options: {
      denyWarnings: true,
      typeAware: true,
      typeCheck: true,
    },
    jsPlugins: [
      {
        name: 'vite-plus',
        specifier: 'vite-plus/oxlint-plugin',
      },
    ],
    rules: {
      'vite-plus/prefer-vite-plus-imports': 'error',
    },
  },
})
