import {
  type SwiftFunction,
  type SwiftStruct,
  isCallbackType,
  parseCallbackType,
  classifyNativeSwiftType,
} from '../parser.js'

import {
  cppIdentifier,
  cppReturnType,
  cppType,
  cppTypeFromCategory,
  findStruct,
  sanitizeId,
  streamElementUsesStringLength,
} from './shared.js'

// Generate C struct typedefs for bridge header
function generateCStructDefs(structs: SwiftStruct[]): string[] {
  const lines: string[] = []
  for (const s of structs) {
    lines.push(`typedef struct {`)
    for (const f of s.fields) {
      const fieldName = cppIdentifier(f.name)
      switch (f.category) {
        case 'int32':
          lines.push(`    int32_t ${fieldName};`)
          break
        case 'int64':
          lines.push(`    int64_t ${fieldName};`)
          break
        case 'double':
          lines.push(`    double ${fieldName};`)
          break
        case 'bool':
          lines.push(`    bool ${fieldName};`)
          break
        case 'string':
          lines.push(`    const char* ${fieldName};`)
          lines.push(`    size_t ${fieldName}_len;`)
          break
      }
    }
    lines.push(`} swift_node_${s.name};`)
    lines.push('')
  }
  return lines
}

// Standalone header with just struct typedefs — imported into Swift via -import-objc-header
export function generateStructsHeader(structs: SwiftStruct[]): string {
  const lines = [
    '// Generated by swift-node — do not edit',
    '#ifndef SWIFT_NODE_STRUCTS_H',
    '#define SWIFT_NODE_STRUCTS_H',
    '',
    '#include <stdint.h>',
    '#include <stdbool.h>',
    '#include <stddef.h>',
    '',
    ...generateCStructDefs(structs),
    '#endif',
  ]
  return lines.join('\n')
}

export function generateBridgeH(
  functions: SwiftFunction[],
  moduleName: string,
  structs: SwiftStruct[] = [],
): string {
  const guard = `${sanitizeId(moduleName).toUpperCase()}_BRIDGE_H`
  const lines: string[] = [
    `#ifndef ${guard}`,
    `#define ${guard}`,
    '',
    '#include <stdint.h>',
    '#include <stdbool.h>',
    '#include <stddef.h>',
    '',
    '#ifdef __cplusplus',
    'extern "C" {',
    '#endif',
    '',
  ]

  // Struct typedefs (before function declarations that reference them)
  if (structs.length > 0) {
    lines.push(...generateCStructDefs(structs))
  }

  for (const fn of functions) {
    if (fn.stream) {
      const params = fn.params.map((p) => {
        const paramName = cppIdentifier(p.name)
        if (p.type.includes('UnsafeMutablePointer<CChar>')) return `char* ${paramName}`
        const pStruct = findStruct(p.type, structs)
        if (pStruct) return `swift_node_${pStruct.name} ${paramName}`
        return `${cppType(p.type)} ${paramName}`
      })
      const valueType =
        fn.stream.transport === 'json'
          ? 'const char*'
          : cppTypeFromCategory(classifyNativeSwiftType(fn.stream.elementType))
      const valueHasLength = streamElementUsesStringLength(
        fn.stream.elementType,
        fn.stream.transport,
      )
      params.push('int64_t subscription_id')
      params.push(`void (*on_value)(int64_t, ${valueType}${valueHasLength ? ', int64_t' : ''})`)
      params.push('void (*on_complete)(int64_t, const char*)')
      lines.push(`void ${fn.symbolName}(${params.join(', ')});`)
      lines.push(`void ${fn.symbolName}_cancel(int64_t subscription_id);`)
      continue
    }

    const ret = cppReturnType(fn.returnType)
    const params = fn.params
      .map((p) => {
        const paramName = cppIdentifier(p.name)
        if (p.bridgeStringResultLength) return `int64_t* ${paramName}`
        if (p.type.includes('UnsafeMutablePointer<UnsafePointer<CChar>?>')) {
          return 'const char** out_error'
        }
        if (p.type.includes('UnsafeMutablePointer<CChar>')) {
          return `char* ${paramName}`
        }
        if (p.promiseCallback) {
          const callbackParams = p.promiseCallback.params
            .flatMap((parameter) => {
              const type = parameter.swiftType
              return classifyNativeSwiftType(type) === 'string'
                ? [`const char*`, 'int64_t']
                : [cppType(type)]
            })
            .join(', ')
          return `void (*${paramName})(void*, ${callbackParams}${callbackParams ? ', ' : ''}void (*)(void*, const char*, int64_t, const char*, int64_t), void*)`
        }
        if (p.promiseCallbackRelease) {
          return `void (*${paramName})(void*)`
        }
        if (isCallbackType(p.type)) {
          // Generate the C callback function pointer signature
          const cb = parseCallbackType(p.type)
          if (cb) {
            const cbParams = cb.params.map((cp) => cppType(cp.swiftType)).join(', ')
            return `void (*${paramName})(${cbParams})`
          }
          return `void (*${paramName})(void)`
        }
        // Check for struct type
        const pStruct = findStruct(p.type, structs)
        if (pStruct) {
          return `swift_node_${pStruct.name} ${paramName}`
        }
        const t = cppType(p.type)
        return `${t} ${paramName}`
      })
      .join(', ')

    // Handle struct return types
    let retType = ret
    const retStruct2 = findStruct(fn.returnType, structs)
    if (retStruct2) {
      retType = `swift_node_${retStruct2.name}`
    }

    lines.push(`${retType} ${fn.symbolName}(${params});`)
  }

  lines.push('', '#ifdef __cplusplus', '}', '#endif', '', `#endif`)
  return lines.join('\n')
}
