import {
  BridgeTransport,
  SwiftFunction,
  SwiftParam,
  SwiftStruct,
  SwiftStructField,
  PromiseCallbackInfo,
  bridgeTransportForType,
  classifySwiftType,
  SwiftTypeCategory,
  isCallbackType,
  parseCallbackType,
  ExportedFunction,
  classifyNativeSwiftType,
  parseSwiftStreamReturnType,
  splitParams,
} from '../parser.js'

import {
  findStruct,
  isNullableType,
  jsName,
  jsParams,
  tsCallbackType,
  tsParamType,
  tsReturnType,
  tsTypeFromNative,
} from './shared.js'

// --- TypeScript definition generation ---

function tsStructType(s: SwiftStruct): string {
  const fields = s.fields.map((f) => {
    let t = 'unknown'
    switch (f.category) {
      case 'int32':
      case 'int64':
      case 'double':
        t = 'number'
        break
      case 'bool':
        t = 'boolean'
        break
      case 'string':
        t = 'string'
        break
    }
    return `  ${f.name}: ${t}`
  })
  return `{\n${fields.join('\n')}\n}`
}

function indentLines(text: string, spaces: number): string {
  const prefix = ' '.repeat(spaces)
  return text
    .split('\n')
    .map((line) => (line.length > 0 ? prefix + line : line))
    .join('\n')
}

export function generateDts(
  functions: SwiftFunction[],
  moduleName: string,
  structs: SwiftStruct[] = [],
): string {
  const lines: string[] = ['// Generated by swift-node — do not edit', '']

  if (functions.some((fn) => fn.stream)) {
    lines.push('declare global {')
    lines.push('  interface SymbolConstructor {')
    lines.push('    readonly dispose: unique symbol')
    lines.push('  }')
    lines.push('}')
    lines.push('')
    lines.push('export interface SwiftNodeSubscription {')
    lines.push('  readonly closed: boolean')
    lines.push('  cancel(): void')
    lines.push('  [Symbol.dispose](): void')
    lines.push('}')
    lines.push('')
  }

  // Generate TypeScript interfaces for structs
  for (const s of structs) {
    lines.push(`export interface ${s.name} ${tsStructType(s)}`)
    lines.push('')
  }

  for (const [index, fn] of functions.entries()) {
    const name = jsName(fn.symbolName, moduleName)

    const jp = jsParams(fn)
    const params = jp.map((p) => {
      if (isCallbackType(p.type)) {
        return `${p.name}: ${tsCallbackType(p.nativeType || p.type)}`
      }
      // Check for struct type — use the clean Swift name, not the C swift_node_ prefix
      const pStructDts = findStruct(p.type, structs)
      if (pStructDts) {
        return `${p.name}: ${pStructDts.name}`
      }
      return `${p.name}: ${tsParamType(p)}`
    })
    if (fn.stream) {
      const value = tsTypeFromNative(fn.stream.elementType, fn.stream.transport === 'json')
      params.push(`onValue: (value: ${value}) => void`)
      params.push('onError?: (error: Error) => void')
      params.push('onComplete?: () => void')
    }

    // Return type: check struct first — use clean Swift name
    const ret = tsReturnType(fn, structs)
    const asyncRet = fn.stream ? 'SwiftNodeSubscription' : fn.isAsync ? `Promise<${ret}>` : ret

    const binding = `__swift_node_${index}`
    lines.push(`declare const ${binding}: (${params.join(', ')}) => ${asyncRet}`)
    lines.push(`export { ${binding} as ${name} }`)
  }

  return lines.join('\n')
}

export function generateDtsCjs(
  functions: SwiftFunction[],
  moduleName: string,
  structs: SwiftStruct[] = [],
): string {
  const lines: string[] = ['// Generated by swift-node — do not edit', '']

  if (functions.some((fn) => fn.stream)) {
    lines.push('declare global {')
    lines.push('  interface SymbolConstructor {')
    lines.push('    readonly dispose: unique symbol')
    lines.push('  }')
    lines.push('}')
    lines.push('')
  }

  lines.push('declare namespace native {')

  if (functions.some((fn) => fn.stream)) {
    lines.push('  interface SwiftNodeSubscription {')
    lines.push('    readonly closed: boolean')
    lines.push('    cancel(): void')
    lines.push('    [Symbol.dispose](): void')
    lines.push('  }')
    lines.push('')
  }

  for (const s of structs) {
    lines.push(indentLines(`interface ${s.name} ${tsStructType(s)}`, 2))
    lines.push('')
  }

  const iface: string[] = []
  for (const fn of functions) {
    const name = jsName(fn.symbolName, moduleName)

    const jp = jsParams(fn)
    const params = jp.map((p) => {
      if (isCallbackType(p.type)) {
        return `${p.name}: ${tsCallbackType(p.nativeType || p.type)}`
      }
      const pStructDts = findStruct(p.type, structs)
      if (pStructDts) {
        return `${p.name}: ${pStructDts.name}`
      }
      return `${p.name}: ${tsParamType(p)}`
    })
    if (fn.stream) {
      const value = tsTypeFromNative(fn.stream.elementType, fn.stream.transport === 'json')
      params.push(`onValue: (value: ${value}) => void`)
      params.push('onError?: (error: Error) => void')
      params.push('onComplete?: () => void')
    }

    const ret = tsReturnType(fn, structs)
    const asyncRet = fn.stream ? 'SwiftNodeSubscription' : fn.isAsync ? `Promise<${ret}>` : ret

    iface.push(`  ${name}(${params.join(', ')}): ${asyncRet}`)
  }

  lines.push('  interface NativeBindings {')
  lines.push(iface.map((line) => `  ${line}`).join('\n'))
  lines.push('  }')
  lines.push('}')
  lines.push('')
  lines.push('declare const native: native.NativeBindings')
  lines.push('export = native')

  return lines.join('\n')
}

// Emitted verbatim into both module formats so generated packages load only
// their declared binary without a runtime dependency.
