import { SwiftFunction } from '../parser.js'
import { jsName } from './shared.js'

function generatedAddonResolverLines(): string[] {
  return [
    `function resolveAddonPath(dir, moduleName) {`,
    `  const isMusl = process.platform === 'linux' && !process.report?.getReport?.().header?.glibcVersionRuntime`,
    `  const target = process.platform + '-' + process.arch + (isMusl ? '-musl' : '')`,
    `  const binaryName = moduleName + '.' + target + '.node'`,
    `  const binaryPath = path.join(dir, ...(process.platform === 'darwin' ? [] : [target]), binaryName)`,
    `  if (existsSync(binaryPath)) return binaryPath`,
    '',
    `  throw new Error(`,
    `    'No .node binary found for ' + target + '.\\n' +`,
    `    'Checked:\\n' +`,
    `    '  ' + binaryPath + '\\n' +`,
    `    "Run 'swift-node build' for this platform and architecture."`,
    `  )`,
    `}`,
  ]
}

// Generate dist_swift-node/index.mjs — ESM entry point. Pure JS (no TS syntax) so
// Node can load it without a TypeScript loader. Types come from index.d.ts.
// .mjs extension ensures ESM parsing regardless of package "type" field.
export function generateEntryMjs(functions: SwiftFunction[], moduleName: string): string {
  const lines = [
    '// Generated by swift-node — do not edit',
    '',
    `import { createRequire } from 'node:module'`,
    `import { fileURLToPath } from 'node:url'`,
    `import path from 'node:path'`,
    '',
    `const require = createRequire(import.meta.url)`,
    `const __dirname = path.dirname(fileURLToPath(import.meta.url))`,
    `const { existsSync } = require('node:fs')`,
    '',
    ...generatedAddonResolverLines(),
    '',
    `const native = require(resolveAddonPath(__dirname, ${JSON.stringify(moduleName)}))`,
    '',
  ]
  for (const [index, fn] of functions.entries()) {
    const name = jsName(fn.symbolName, moduleName)
    lines.push(`const __swift_node_${index} = native[${JSON.stringify(name)}]`)
  }
  if (functions.length > 0) {
    lines.push('')
  }
  for (const [index, fn] of functions.entries()) {
    const name = jsName(fn.symbolName, moduleName)
    lines.push(`export { __swift_node_${index} as ${name} }`)
  }
  return lines.join('\n')
}

// Generate dist_swift-node/index.cjs — CJS entry point for require() consumers.
export function generateEntryCjs(functions: SwiftFunction[], moduleName: string): string {
  const lines = [
    '// Generated by swift-node — do not edit',
    `const path = require('node:path')`,
    `const { existsSync } = require('node:fs')`,
    '',
    ...generatedAddonResolverLines(),
    '',
    `const native = require(resolveAddonPath(__dirname, ${JSON.stringify(moduleName)}))`,
    '',
    `module.exports = {`,
  ]
  for (const fn of functions) {
    const name = jsName(fn.symbolName, moduleName)
    lines.push(`  ${JSON.stringify(name)}: native[${JSON.stringify(name)}],`)
  }
  lines.push('}')
  return lines.join('\n')
}

// Generate the TypeScript source entry created by `swift-node init`. Package
// exports point straight at dist_swift-node; this file is the convenient source
// entry for a project's own TypeScript code.
export function generateSourceEntryTs(): string {
  return "export * from '../dist_swift-node/index.mjs'\n"
}
