import { ExportedFunction, SwiftStruct } from '../../parser.js'
import { promiseCallbackInfo } from '../shared.js'
import { generatePromiseCallbackSwiftRuntime } from './callbacks.js'
import { generateSingleWrapper } from './function-wrapper.js'
import { generateSingleStreamWrapper, generateSwiftStreamRuntime } from './streams.js'

export { exportedToSwiftFunctions } from './ir.js'

// Generate Swift wrapper functions containing @_cdecl exports.
export function generateWrappersSwift(
  exported: ExportedFunction[],
  moduleName: string,
  structs: SwiftStruct[] = [],
  codableTypes: Iterable<string> = [],
): string {
  if (exported.length === 0) return ''

  const lines: string[] = [
    '// Generated by swift-node — do not edit',
    `// Source annotation: // @swift-node:export`,
    '',
    'import Foundation',
    '',
    `private func swiftNodeCopyUTF8(_ value: String) -> UnsafeMutablePointer<CChar>? {
    let bytes = Array(value.utf8)
    guard let destination = malloc(bytes.count + 1)?.assumingMemoryBound(to: CChar.self) else { return nil }
    bytes.withUnsafeBytes { source in
        if !bytes.isEmpty { memcpy(destination, source.baseAddress!, bytes.count) }
    }
    destination[bytes.count] = 0
    return destination
}`,
    '',
    `private func swiftNodeDecodeUTF8(_ value: UnsafePointer<CChar>, _ length: Int) -> String {
    String(decoding: UnsafeRawBufferPointer(start: value, count: length).bindMemory(to: UInt8.self), as: UTF8.self)
}`,
    '',
  ]

  if (exported.some((fn) => fn.isStream)) {
    lines.push(generateSwiftStreamRuntime())
    lines.push('')
  }

  for (const fn of exported) {
    for (const parameter of fn.params) {
      if (promiseCallbackInfo(parameter.type)) {
        lines.push(generatePromiseCallbackSwiftRuntime(fn, parameter))
        lines.push('')
      }
    }
  }

  for (const fn of exported) {
    lines.push(
      fn.isStream
        ? generateSingleStreamWrapper(fn, moduleName, structs, codableTypes)
        : generateSingleWrapper(fn, moduleName, structs, codableTypes),
    )
    lines.push('')
  }

  return lines.join('\n')
}
