import { ExportedFunction, SwiftStruct } from '../../parser.js'
import { promiseCallbackInfo } from '../shared.js'
import { generatePromiseCallbackSwiftRuntime } from './callbacks.js'
import { generateSingleWrapper } from './function-wrapper.js'
import { generateSingleStreamWrapper, generateSwiftStreamRuntime } from './streams.js'

export { exportedToSwiftFunctions } from './ir.js'

// Generate Swift wrapper functions containing @_cdecl exports.
export function generateWrappersSwift(
  exported: ExportedFunction[],
  moduleName: string,
  structs: SwiftStruct[] = [],
  codableTypes: Iterable<string> = [],
): string {
  if (exported.length === 0) return ''

  const lines: string[] = [
    '// Generated by swift-node — do not edit',
    `// Source annotation: // @swift-node:export`,
    '',
    'import Foundation',
    '',
    `public indirect enum SwiftNodeJSONValue: Sendable {
    case null
    case bool(Bool)
    case number(Double)
    case string(String)
    case array([SwiftNodeJSONValue])
    case object([String: SwiftNodeJSONValue])
}

extension SwiftNodeJSONValue: Encodable {
    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .null:
            try container.encodeNil()
        case let .bool(value):
            try container.encode(value)
        case let .number(value):
            try container.encode(value)
        case let .string(value):
            try container.encode(value)
        case let .array(value):
            try container.encode(value)
        case let .object(value):
            try container.encode(value)
        }
    }
}

public protocol SwiftNodeStructuredError: Error {
    var code: String { get }
    var message: String { get }
    var details: [String: SwiftNodeJSONValue] { get }
}

public extension SwiftNodeStructuredError {
    var message: String { localizedDescription }
    var details: [String: SwiftNodeJSONValue] { [:] }
}

private struct SwiftNodeErrorEnvelope: Encodable {
    let message: String
    let code: String?
    let details: [String: SwiftNodeJSONValue]?
}
`,
    '',
    `private func swiftNodeCopyUTF8(_ value: String) -> UnsafeMutablePointer<CChar>? {
    let bytes = Array(value.utf8)
    guard let destination = malloc(bytes.count + 1)?.assumingMemoryBound(to: CChar.self) else { return nil }
    bytes.withUnsafeBytes { source in
        if !bytes.isEmpty { memcpy(destination, source.baseAddress!, bytes.count) }
    }
    destination[bytes.count] = 0
    return destination
}`,
    '',
    `private func swiftNodeEncodeError(_ envelope: SwiftNodeErrorEnvelope) -> UnsafeMutablePointer<CChar> {
    let fallback = #"{"message":"swift-node failed to encode an error"}"#
    let encoded = (try? JSONEncoder().encode(envelope)).flatMap { String(data: $0, encoding: .utf8) } ?? fallback
    return swiftNodeCopyUTF8(encoded)!
}

private func swiftNodeBridgeError(_ error: any Error) -> UnsafeMutablePointer<CChar> {
    if let structured = error as? any SwiftNodeStructuredError {
        return swiftNodeEncodeError(
            SwiftNodeErrorEnvelope(
                message: structured.message,
                code: structured.code,
                details: structured.details
            )
        )
    }
    return swiftNodeEncodeError(
        SwiftNodeErrorEnvelope(message: error.localizedDescription, code: nil, details: nil)
    )
}

private func swiftNodeBridgeError(_ message: String) -> UnsafeMutablePointer<CChar> {
    swiftNodeEncodeError(SwiftNodeErrorEnvelope(message: message, code: nil, details: nil))
}`,
    '',
    `private func swiftNodeDecodeUTF8(_ value: UnsafePointer<CChar>, _ length: Int) -> String {
    String(decoding: UnsafeRawBufferPointer(start: value, count: length).bindMemory(to: UInt8.self), as: UTF8.self)
}`,
    '',
  ]

  if (exported.some((fn) => fn.isStream)) {
    lines.push(generateSwiftStreamRuntime())
    lines.push('')
  }

  for (const fn of exported) {
    for (const parameter of fn.params) {
      if (promiseCallbackInfo(parameter.type)) {
        lines.push(generatePromiseCallbackSwiftRuntime(fn, parameter))
        lines.push('')
      }
    }
  }

  for (const fn of exported) {
    lines.push(
      fn.isStream
        ? generateSingleStreamWrapper(fn, moduleName, structs, codableTypes)
        : generateSingleWrapper(fn, moduleName, structs, codableTypes),
    )
    lines.push('')
  }

  return lines.join('\n')
}
